name: PyBuilder Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: [SonarCloudSCan]  # Make sure this job runs after the sonarcloud job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint src/main/python/python_api.py

  build_and_test:
    runs-on: ubuntu-latest
    needs: [lint]  # Make sure this job runs after the sonarcloud job
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
           
      - name: Install PyBuilder
        run: | 
          python -m pip install --upgrade pip
          pip install pybuilder
     
      - name: Build and Test
        run: pyb

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/reports  

      - name: List Files  # Optional step
        run: |
          ls -R
  SonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=vishnubitsmtech
              -Dsonar.projectKey=PythonApiDemo
              -Dsonar.python.coverage.reportPaths=coverage.xml